#!/bin/sh

### BEGIN INIT INFO
# Provides: motd-tail-update
# Required-Start: $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:
# Default-Start: 0 1 2 3 4 5 6
# Default-Stop: 
# Short-Description: Update motd.tail
### END INIT INFO

. /lib/lsb/init-functions

SECUNDUS=$(cat /proc/uptime | sed -e 's/ [0-9]*.*//g')
HORUS=$(echo "scale=2; ""$SECUNDUS""/3600" | bc)

#printf "Haven't slept in %s hours..." "$HORUS"
echo "Beware, I've not slept in $HORUS hours..." > /etc/motd.tail
