#!/bin/sh

# This script gets called by 'darwin-shutdown' at shutdown.
#   'darwin-shutdown-linker' is copied to '/etc/init.d/darwin-shutdown' during
#     setup, which is sym-linked into rc0.d and rc6.d as 'K18shutdownscript'

/usr/bin/mpg321 "/usr/share/sounds/byebyte.mp3"

# ZeebZob
# espeak -ven-us+f3 -a 25 -s 130 "see you later meatbag."

# Damdeok
# espeak -ven-us+m1 -a 25 -s 130 "see you later meatbag."

# Darfo
# espeak -vit+m3 -a 25 -s 130 "gud bay mit bhag."
# espeak -vit+m3 -a 25 -s 130 "aym redi whenever you ar"

