#!/bin/sh

# This script gets called by 'darwin-shutdown' at shutdown.
#   'darwin-shutdown-linker' is copied to '/etc/init.d/darwin-shutdown' during
#     setup, which is sym-linked into rc0.d and rc6.d as 'K18shutdownscript'

# /usr/bin/madplay "/Data/mp3/byebyte.mp3"

# ZeebZob
# espeak -ven+f3 -a 50 -s 130 "bye bye"
espeak -ven+f3 -a 50 -s 130 "nighty night"

# Damdeok
# espeak -ven-us+m1 -a 25 -s 130 "see you later meatbag."

# Darfo
# espeak -vit+m3 -a 25 -s 130 "gud bay mit bhag."
# espeak -vit+m3 -a 25 -s 130 "aym redi whenever you ar"

